### ISSUE TITLE
Initial development roadmap

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/basgit#7]
Instead of creating a dedicate issue for each of these, I'll collect ideas for initial development here.

### Phase 0 ([PR](https://github.com/LukasKalbertodt/basgit/pull/8))

- [x] Minor cleanup & merge current progress into master
- [x] Update `README.md` and `CONTRIBUTE.md` to reflect the current status of the project
- [x] Make Travis work with diesel.rs and database stuff

### Phase 1: User handling ([PR](https://github.com/LukasKalbertodt/basgit/pull/11))

- [x] DB connection pooling via `r2d2` ([`r2d2-diesel`](https://github.com/diesel-rs/r2d2-diesel))
- [x] Proper user session cookie
- [x] Proper login page with feedback on failure
- [ ] User signup process (*postponed*: not that important now)
- [ ] Maybe add "login via GitHub" (*postponed*: OAuth API of GitHub needs a fixed URL or something...)
- [x] Rather empty user page

### Phase 2: Basic baskets ([PR](https://github.com/LukasKalbertodt/basgit/pull/13))

- [x] Teach the DB about "baskets"
- [x] List baskets of user on user page & list all existing baskets on the index page (temporary)
- [x] Form to create basket
- [x] Route for page showing the basket's contents (pretty empty at first)

### Phase 3: Git 

- [ ] Create a git repository for each basket
  - probably important: think about where to put the repository
- [ ] Show basic git information on basket page
- [ ] Make it possible to traverse files of a basket's git repo
  - ... but don't spend too much time on that; this is not really the interesting part of this project. And while file browsing like on GitHub is somewhat needed for the end version, there should be more focus on the "facade" stuff.
  - Maybe even think about making git file browsing just another facade and add multiple item types to a basket... stuff like that
- [ ] Think about making the git repository directly accessible
  - ... but again, don't spend too much time on this. If it turns out that a bit more complicated ssh server config is needed, this step should be skipped for now.
- [ ] Probably as a requirement for facades and file browsing, I should think about a standard API interface. Of course REST & JSON is a de-facto standard, but it has a number of downsides. Apart from that, I should develop a system which makes it easy to pre render websites when first accessing then AND to update the site via JS by requesting data from the API. This is probably not easy at all, but should lie an important foundation for everything that follows. Keywords: Falcor by Netflix, GraphQL by Facebook.

### Phase 4: Facades

- [ ] Design the whole thing, basically.
- [ ] Make bullet points for "Phase 4" more useful...
- ...

## At some time

- [ ] Think about testing ([click](https://rocket.rs/guide/testing/)) (Do this rather early!)
- [x] Think about auto deploy to heroku via Travis-CI (see #12)
- [ ] Develop a standard style which is similar to GitHub's but still notably different 
- [ ] Design a logo
